// برچسب فارسی برای گروه‌های جنسیت و زیردسته‌های لینک برند

export const GENDER_LABELS: Record<string, string> = {
  w: "زنانه",
  m: "مردانه",
  k: "بچگانه",
  home: "خانه و آشپزخانه",
  cats: "دسته‌بندی‌ها",
};

export const SUB_LABELS: Record<string, string> = {
  base: "همهٔ محصولات",
  clothing: "پوشاک",
  dress: "پیراهن / ماکسی",
  pants: "شلوار",
  jeans: "جین",
  tshirt: "تیشرت",
  blouse: "بلوز",
  shirt: "پیراهن مردانه",
  jacket: "کت / کاپشن",
  blazer: "بلیزر",
  coat: "پالتو / مانتو",
  skirt: "دامن",
  shorts: "شلوارک",
  sweatshirt: "سوییشرت / هودی",
  knitwear: "بافت",
  suit: "ست / کت‌شلوار",
  underwear: "لباس زیر",
  swimwear: "لباس شنا",
  pajamas: "پیژامه",
  leggings: "لگ",
  sport: "لباس ورزشی",
  sportswear: "لباس ورزشی",
  bra: "سوتین ورزشی",
  shoes: "کفش",
  sneakers: "کتونی / اسنیکر",
  boots: "بوت",
  sandals: "صندل",
  heels: "پاشنه‌دار",
  football_shoes: "کفش فوتبال",
  bags: "کیف",
  handbags: "کیف دستی",
  backpack: "کوله‌پشتی",
  wallets: "کیف پول",
  belts: "کمربند",
  jewelry: "جواهرات",
  scarves: "شال / روسری",
  sunglasses: "عینک آفتابی",
  watches: "ساعت",
  accessories: "اکسسوری",
  socks: "جوراب",
  tights: "جوراب شلواری",
  hats: "کلاه",
  perfume: "عطر",
  beauty: "آرایشی",
  makeup: "آرایشی",
  face: "آرایش صورت",
  eye: "آرایش چشم",
  lips: "رژ لب",
  nails: "لاک / ناخن",
  skincare: "مراقبت پوست",
  haircare: "مراقبت مو",
  haircolor: "رنگ مو",
  men: "مردانه",
  // خانه
  kitchen: "آشپزخانه",
  dining: "سفره و پذیرایی",
  bedroom: "اتاق خواب",
  bathroom: "حمام",
  decor: "دکوراسیون",
  cookware: "قابلمه و تابه",
  mugs: "فنجان و ماگ",
  bedding: "سرویس خواب",
  curtains: "پرده",
  towels: "حوله",
  rugs: "فرش",
  furniture: "مبلمان",
  mattress: "تشک",
  pillows: "بالش",
  electrical: "لوازم برقی",
  knives: "چاقو",
  pans: "تابه",
  pots: "قابلمه",
  irons: "اتو",
  kettles: "کتری برقی",
  // کودک
  girl: "دخترانه",
  boy: "پسرانه",
  teen_girl: "نوجوان دختر",
  teen_boy: "نوجوان پسر",
  baby: "نوزاد",
  baby_girl: "نوزاد دختر",
  baby_boy: "نوزاد پسر",
  girl_shoes: "کفش دخترانه",
  boy_shoes: "کفش پسرانه",
  strollers: "کالسکه",
  carseats: "صندلی خودرو",
  feeding: "تغذیه",
  toys: "اسباب‌بازی",
  care: "مراقبت",
  equipment: "تجهیزات",
  watsons: "",
};

export function subLabel(key: string): string {
  return SUB_LABELS[key] || key;
}
